name: Simple Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the code
      - uses: actions/checkout@v4

      # 2. Set up Node.js (use LTS)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Install dependencies
      - run: npm install --legacy-peer-deps --no-audit --progress=false

      # 4. Run ESLint to catch unresolved imports (case-sensitive)
      - run: npm run lint

      # 5. Build the project
      - run: npm run build 